### ISSUE TITLE
Issue in mpv.py

### ISSUE THREAD

**Issue by Aristocles** [gustaebel/python-mpv#1]
Firstly, thanks for the script.

I ran in to a problem running it. I've placed relevant import:

```
import os, subprocess, time, serial, sys, threading
from itertools import cycle
from mpv import MPV
```

Then when I try to run the script I get.

```
Traceback (most recent call last):
  File "./parse3.py", line 5, in <module>
    from mpv import MPV
  File "/home/pi/bin/mpv.py", line 483
    def command(self, *args, timeout=1):
                                   ^
SyntaxError: invalid syntax

```

Anyone know what the issue here is? I am not very good at Python so it could be something simple which I am missing. Thanks.

**Comment by gustaebel** [comment]
Are you using Python 2?

**Comment by Aristocles** [comment]
Yes. v2.7.9

**Comment by gustaebel** [comment]
Yes, that's the problem. mpv.py is Python 3 only.

**Comment by Aristocles** [comment]
Ah, that explains it. Thanks.
