### ISSUE TITLE
Control already running MPV instance

### ISSUE THREAD

**Issue by beli-sk** [gustaebel/python-mpv#5]
Hi,
is there a way I can control an already running MVP instance if I have the IPC socket path? MPVBase class starts it's own instance and reading the source I haven't found an easy way to skip this in a class inheriting from your MPV class.
Thank you.

**Comment by gustaebel** [comment]
Actually, I think this should not be too hard. Just override the respective methods from the MPVBase class, so that _start_process() and _stop_process() are empty, and _start_socket() connects to the socket with the right pathname. Have you tried something like that?

**Comment by beli-sk** [comment]
Seems to work, though I had to override a few more things, like `_start_socket` not to hang if the socket is not found or `close` not to pass _quit_ command. And also added context manager methods so I don't forget to _close_ as it keeps the comm thread hanging around. This is what I used:

```python
class MPVRemote(MPV):
    def _start_process(self):
        pass

    def _stop_process(self):
        pass

    def _prepare_socket(self):
        pass

    def _start_socket(self):
        self._sock = socket.socket(socket.AF_UNIX)
        self._sock.connect(self._sock_filename)

    def is_running(self):
        return self._is_running

    def __init__(self, socket_path, debug=False):
        self._sock_filename = socket_path
        self._is_running = True
        super().__init__(debug=debug)

    def close(self):
        self._is_running = False
        super().close()

    def __enter__(self):
        return self

    def __exit__(self, *args, **kwargs):
        self.close()
```

Thanks for the tip.
